export enum RoutesEnum {
  Home = 'home',
  Golapp = 'golapp',
  Ligas = 'ligas',
  Torneios = 'torneios',
  Embaixadores = 'embaixadores',
  'Equipa Golapp' = 'equipa golapp',
  'Como Pagar?' = 'como pagar?',
  Eventos = 'eventos',
  Tabelas = 'tabelas',
  Resultados = 'resultados',
  Calendario = 'calendário',
  Jogadores = 'jogadores',
  Equipas = 'equipas',
  Transmissao = 'transmissão',
  Notiticas = 'notícias',
  Arbitros = 'árbitros',
  TermosDeUso = 'termos de uso',
  PoliticasDePrivacidade = 'políticas de privacidade',
  PerguntasMaisFrequentes = 'perguntas mais frequentes',
}

export const Routes: Record<RoutesEnum, string> = {
  [RoutesEnum.Home]: '/',
  [RoutesEnum.Golapp]: '/about-us',
  [RoutesEnum.Ligas]: '/leagues',
  [RoutesEnum.Torneios]: '/tournaments',
  [RoutesEnum.Embaixadores]: '/embassors',
  [RoutesEnum['Equipa Golapp']]: '/golapp-team',
  [RoutesEnum['Como Pagar?']]: '/how-to-pay',
  [RoutesEnum.Eventos]: '/events',
  [RoutesEnum.Tabelas]: '/tables',
  [RoutesEnum.Resultados]: '/results',
  [RoutesEnum.Calendario]: '/calendars',
  [RoutesEnum.Jogadores]: '/players',
  [RoutesEnum.Equipas]: '/teams',
  [RoutesEnum.Transmissao]: '/transmission',
  [RoutesEnum.Notiticas]: '/news',
  [RoutesEnum.Arbitros]: '/referees',
  [RoutesEnum.TermosDeUso]: '/terms-of-use',
  [RoutesEnum.PoliticasDePrivacidade]: '/privacy-policy',
  [RoutesEnum.PerguntasMaisFrequentes]: '/faq',
};
